# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 09:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.SmallIntegerField(verbose_name='手机号')),
                ('pwd', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='密码')),
                ('identifying_code', models.CharField(max_length=20, verbose_name='验证码')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
